/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetCwd */

#ifndef _Included_GetCwd
#define _Included_GetCwd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetCwd
 * Method:    getCWD
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GetCwd_getCWD
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
